version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webapp
    depends_on:
    - postgres


  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - webapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - webapp

networks:
  webapp:

volumes:
  postgres_data: